on:
  push:
    branches:
      - gh-pages
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: yarn install
        run: yarn install

      - name: gatsby build
        env:
          GH_API_KEY: ${{ GIST_ID }}
        run: yarn build

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ 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 }}
          GH_PAT: ${{ GIST_ID }}
          BUILD_DIR: 'public/'
